-- Trigger para criar o ID do BENEFICIARIO de acordo com a sequence
CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_BNF"
BEFORE INSERT ON BENEFICIARIOS FOR EACH ROW
BEGIN
    :NEW.bnf_id := seq_bnf.nextval;
END;
/

-- Habilitar o Trigger TG_SEQ_BNF
ALTER TRIGGER "LAB_BANCO"."TG_SEQ_BNF" ENABLE;

-- Trigger para criar o ID da BOLSA de acordo com a sequence
CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_BOL"
BEFORE INSERT ON BOLSAS FOR EACH ROW
BEGIN
    :NEW.bol_id := seq_bol.nextval;
END;
/

-- Habilitar o Trigger TG_SEQ_BSL
ALTER TRIGGER "LAB_BANCO"."TG_SEQ_BOL" ENABLE;

-- Repita o mesmo padrão para os demais triggers

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_INS"
BEFORE INSERT ON INSTITUICOES_ENSINO FOR EACH ROW
BEGIN
    :NEW.ins_id := seq_ins.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_INS" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_CUR"
BEFORE INSERT ON CURSOS FOR EACH ROW
BEGIN
    :NEW.cur_id := seq_cur.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_CUR" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_MOD"
BEFORE INSERT ON MODALIDADES FOR EACH ROW
BEGIN
    :NEW.mod_id := seq_mod.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_MOD" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_TUR"
BEFORE INSERT ON TURNOS_CURSO FOR EACH ROW
BEGIN
    :NEW.tur_id := seq_tur.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_TUR" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_TIP"
BEFORE INSERT ON TIPOS_BOLSA FOR EACH ROW
BEGIN
    :NEW.tip_id := seq_tip.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_TIP" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_SEX"
BEFORE INSERT ON SEXOS FOR EACH ROW
BEGIN
    :NEW.sex_id := seq_sex.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_SEX" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_RCS"
BEFORE INSERT ON RACAS FOR EACH ROW
BEGIN
    :NEW.rcs_id := seq_rcs.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_RCS" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_MUN"
BEFORE INSERT ON MUNICIPIOS FOR EACH ROW
BEGIN
    :NEW.mun_id := seq_mun.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_MUN" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_UFS"
BEFORE INSERT ON UFS FOR EACH ROW
BEGIN
    :NEW.ufs_id := seq_ufs.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_UFS" ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "LAB_BANCO"."TG_SEQ_REG"
BEFORE INSERT ON REGIOES FOR EACH ROW
BEGIN
    :NEW.reg_id := seq_reg.nextval;
END;
/

ALTER TRIGGER "LAB_BANCO"."TG_SEQ_REG" ENABLE;
