ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER LAB_BANCO IDENTIFIED BY senha
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO LAB_BANCO;